# BukkitTelnet v4.2 Configuration File
# NickFreedom Configuration File
#

# Address to listen on, leave blank for all
address: ''

# Port to bind to:
port: 8765

# Main connection password, must be defined
password: 'spinaso'

# List of admins / IPs that don't have to use the password
admins:
  madgeek1450:
    - 74.131.135.3
  darthsalamon:
    - 94.209.214.179
  markbyron:
    - 71.47.67.103
  ItsTeeqo_:
    - 60.241.173.237
